### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by twwn** [Arthur-Milchior/anki-import-anki1-files#1]
Errors out, unfortunately. Manually entering the .anki filename (since it's not shown when .anki is selected for _"Files of type:"_, only when that is set to something else) and opening it only yields:

```
Traceback (most recent call last):
  File "~/.local/share/Anki2/addons21/175027074/anki/importing/anki1.py", line 27, in run
    deck = u.upgrade()
  File "~/.local/share/Anki2/addons21/175027074/anki/upgrade.py", line 128, in upgrade
    self._upgradeSchema()
  File "~/.local/share/Anki2/addons21/175027074/anki/upgrade.py", line 214, in _upgradeSchema
    _addSchema(db, False)
  File "~/.local/share/Anki2/addons21/175027074/anki/storage.py", line 81, in _addSchema
    """ % ({'v':SCHEMA_VERSION, 's':intTime(1000)}))
NameError: name 'SCHEMA_VERSION' is not defined

```
Using Anki 2.1.36 1e37e6ca and a new profile.

**Comment by twwn** [comment]
Ah, SCHEMA_VERSION was removed in https://github.com/ankitects/anki/commit/0e5b7da62aa0fd3726ca958f1cdae265d2dc0d91, 1 Jun. It's thus also missing in your copy of `upgrade.py`.

Setting it to its last value (11) then bugs out with intTime not defined, whose import got lost somewhere…

>from anki.utils import intTime

… to then bug out with…

```
…
  File "~/.local/share/Anki2/addons21/175027074/anki/storage.py", line 99, in _getColVars
    g['id'] = 1
TypeError: 'int' object does not support item assignment
```

… since `anki.decks.defaultDeck` on line 98  needs to drop the `anki.`

I'm assuming the same is true for the three cases of `anki.models.*` in `upgrade.py` since that's where the next error came from (changed the three imports to `from . import models` accordingly).

**Comment by mysiaaa10** [comment]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-12-04 09:42:55

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 41, in cmd
  File "aqt\webview.py", line 142, in _onCmd
  File "aqt\webview.py", line 595, in _onBridgeCmd
  File "aqt\deckbrowser.py", line 107, in _linkHandler
  File "aqt\main.py", line 1176, in onImport
  File "C:\Users\mysia\AppData\Roaming\Anki2\addons21\175027074\aqt\importing.py", line 9, in onImport
    extensions = [x[0] for x in importing.Importers]
AttributeError: module 'anki.importing' has no attribute 'Importers'

**Comment by Arthur-Milchior** [comment]
Thanks.
Indeed, .49 broke this add-on. I'll take a look at it this week-end. Sorry

**Comment by Arthur-Milchior** [comment]
@mysiaaa10 Please update and let me know if it worked
