### ISSUE TITLE
Error on Import

### ISSUE THREAD

**Issue by Kurax01** [Arthur-Milchior/anki-import-anki1-files#3]
Im new to this community so i dont really know what to say. There is an error when importing a file

Import fehlgeschlagen. Die Fehlermeldung lautet:
Traceback (most recent call last):
  File "aqt\importing.py", line 404, in on_done
  File "concurrent\futures\_base.py", line 432, in result
  File "concurrent\futures\_base.py", line 388, in __get_result
  File "concurrent\futures\thread.py", line 57, in run
  File "C:\Users\*NAME*\AppData\Roaming\Anki2\addons21\175027074\anki\importing\anki1.py", line 17, in run
    res = u.check(self.file)
  File "C:\Users\*NAME*\AppData\Roaming\Anki2\addons21\175027074\anki\upgrade.py", line 39, in check
    res = self._fix(self.tmppath)
  File "C:\Users\*NAME*\AppData\Roaming\Anki2\addons21\175027074\anki\upgrade.py", line 108, in _fix
    from oldanki import DeckStorage
ModuleNotFoundError: No module named 'oldanki'

Any way to fix this or is the file forever broken?
Best regards

**Comment by Arthur-Milchior** [comment]
Hi,

Which version of anki are you using ?
Can you please share the deck you are using, so that I can test myself?

**Comment by Kurax01** [comment]
Hello,

I use Anki 2.1.35.
This is the deck:
[http://www.tanos.co.uk/jlpt/jlpt4/vocab/n4-vocab-kanji-hiragana.anki](url)

Best regards

**Comment by Arthur-Milchior** [comment]
Hi,

Thanks for the report. 
I don't really know why it stopped working, that's confusing. But it should be repaired. Took me far more time than I expected, but it's done.

Plesae let me know whether it still bugs for you

**Comment by Kurax01** [comment]
Thanks for the quick reply. However i still get an error when loading

Import fehlgeschlagen. Die Fehlermeldung lautet:
Traceback (most recent call last):
  File "aqt\importing.py", line 404, in on_done
  File "concurrent\futures\_base.py", line 432, in result
  File "concurrent\futures\_base.py", line 388, in __get_result
  File "concurrent\futures\thread.py", line 57, in run
  File "C:\Users\Tobias\AppData\Roaming\Anki2\addons21\175027074\anki\importing\anki1.py", line 17, in run
    res = u.check(self.file)
  File "C:\Users\Tobias\AppData\Roaming\Anki2\addons21\175027074\anki\upgrade.py", line 40, in check
    res = self._fix(self.tmppath)
  File "C:\Users\Tobias\AppData\Roaming\Anki2\addons21\175027074\anki\upgrade.py", line 111, in _fix
    from oldanki import DeckStorage
  File "C:\Users\Tobias\AppData\Roaming\Anki2\addons21\175027074\oldanki\__init__.py", line 53, in <module>
    from oldanki.deck import DeckStorage
  File "C:\Users\Tobias\AppData\Roaming\Anki2\addons21\175027074\oldanki\deck.py", line 15, in <module>
    from oldanki.db import *
  File "C:\Users\Tobias\AppData\Roaming\Anki2\addons21\175027074\oldanki\db.py", line 26, in <module>
    from sqlalchemy import (Table, Integer, Float, Column, MetaData,
  File "C:\Users\Tobias\AppData\Roaming\Anki2\addons21\175027074\sqlalchemy\__init__.py", line 8, in <module>
    from . import util as _util  # noqa
  File "C:\Users\Tobias\AppData\Roaming\Anki2\addons21\175027074\sqlalchemy\util\__init__.py", line 14, in <module>
    from ._collections import coerce_generator_arg  # noqa
  File "C:\Users\Tobias\AppData\Roaming\Anki2\addons21\175027074\sqlalchemy\util\_collections.py", line 16, in <module>
    from .compat import binary_types
  File "C:\Users\Tobias\AppData\Roaming\Anki2\addons21\175027074\sqlalchemy\util\compat.py", line 331, in <module>
    time_func = time.clock
AttributeError: module 'time' has no attribute 'clock'

Best regards

**Comment by Arthur-Milchior** [comment]
When you mean "loading" do you mean: when you try to load the deck in your collection, or when you try to load anki with this add-on ?
Did you update this add-on to its newer version ? (Sorry, I know it may seems silly to ask, but sometime that's just the problem)

**Comment by Kurax01** [comment]
When i started anki it asked me to update the add-on and so I did. Then I clicked on 'Import' and chose it (-> error). I also restarted anki to verify there was no problem with the add-on update.

**Comment by Arthur-Milchior** [comment]
Please update and try again
I think I found the error, which was specific to windows

I don' have a windows so I can't try

As a side note, last tiem, you hidden your user name. This time you showed it in the error message. You may or may not want to correct that

**Comment by Kurax01** [comment]
Hey
Ok so now its working fine. I could add the deck. Thanks for all your effort and quick replies

Best regards

**Comment by Arthur-Milchior** [comment]
You're welcome. Thanks for those detailed feedback.
