### ISSUE TITLE
Bombed out loading an old deck....

### ISSUE THREAD

**Issue by klsmith300** [Arthur-Milchior/anki-import-anki1-files#4]
I'm returning to Anki after some time. I have an old deck that I'm wanting to pull in, but had this plugin recommended based o the number. Now with the plugin installed, I get this new error message. The version used to develop the old deck was 2.0.3. 

==== Stack Trace provided by the app: ========================
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-13 22:05:17

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons21\175027074\anki\importing\anki1.py", line 29, in run
    deck = u.upgrade()
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons21\175027074\anki\upgrade.py", line 133, in upgrade
    self._upgradeSchema()
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons21\175027074\anki\upgrade.py", line 199, in _upgradeSchema
    from anki.utils import minimizeHTML
ImportError: cannot import name 'minimizeHTML' from 'anki.utils' (unknown location)

**Comment by matthiashaack** [comment]
Just had the same issue so I opened https://github.com/ankitects/anki/issues/2111 to let them know their assumptions were wrong. This happened for me on this deck http://www.tanos.co.uk/jlpt/jlpt1/vocab/n1-vocab-kanji-hiragana.anki 

I think it started failing with Anki version 2.1.50

**Comment by Arthur-Milchior** [comment]
Thanks @matthiashaack for sharing the deck.
That'll be helpful to reproduce and debug.

@klsmith300: I'm confused. You created an anki1 deck with anki 2.0.3? I would have thought that anki1 decks were created with anki1, not anki2.
But I never used anki 2.0.3 so I don't know

**Comment by Arthur-Milchior** [comment]
@klsmith300 Sorry for not having seen this first report. Too much things going through on github. Thanks a lot @matthiashaack for replying to it which brang it to my attention.
Please update and let me know if it works.
